authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='basket'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.edit, name='edit'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', mainapp.contact, name='contact'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

    def __str__(self):
        return f'{self.name} ({self.category.name})'


class Contact(models.Model):
    phone = models.CharField(verbose_name='номер телефона', max_length=128, unique=True)
    email = models.EmailField(verbose_name='email')
    city = models.CharField(verbose_name='город', max_length=128)
    address = models.CharField(verbose_name='адрес', max_length=128)

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'

    def __str__(self):
        return f'{self.phone} {self.city}'

mainapp/views.py
from random import sample

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from mainapp.models import Product, ProductCategory, Contact


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.filter(is_active=True)

    return sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category, is_active=True). \
                        exclude(pk=hot_product.pk)[:3]

    return same_products


def main(request):
    title = 'главная'
    products = Product.objects.filter(is_active=True)[:3]
    context = {
        'title': title,
        'products': products,
        'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/index.html', context)


def products(request, pk=None, page=1, items_counts=2):
    title = 'продукты'
    links_menu = ProductCategory.objects.filter(is_active=True)

    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = Product.objects.filter(is_active=True).order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk, is_active=True).order_by('-price')

        paginator = Paginator(products, items_counts)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
            'basket': get_basket(request.user),
        }

        return render(request, 'mainapp/products_list.html', context)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    context = {
        'title': title,
        'links_menu': links_menu,
        'same_products': same_products,
        'hot_product': hot_product,
        'basket': get_basket(request.user),

    }
    return render(request, 'mainapp/products.html', context)


def contact(request):
    title = 'контакты'
    contacts = Contact.objects.all()
    context = {
        'title': title,
        'contacts': contacts,
        'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/contact.html', context)


def product(request, pk):
    product_item = get_object_or_404(Product, pk=pk)

    content = {
        'title': product_item.name,
        'links_menu': ProductCategory.objects.all(),
        'product': product_item,
        'basket': get_basket(request.user),
        'same_products': get_same_products(product_item)
    }

    return render(request, 'mainapp/product.html', content)

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static "css/style.css" %}">
	    <link rel="stylesheet" href="{% static "fonts/font-awesome/css/font-awesome.css" %}">
    {% endblock %}
</head>
<body>
	<div class="container">

        {% block menu %}
            <div class="hero-white">
                <div class="header clearfix">
                    <a href="#" class="logo"></a>
                    {% include 'mainapp/includes/inc_main_menu.html' %}
                </div>
            </div>
        {% endblock %}

		{% block content %}
        {% endblock %}

		<div class="clr"></div>

	</div>

    {% block footer %}
        <div class="footer">
            <div class="clearfix">
                <div class="text-footer">
                    <h3>контакты</h3>
                </div>
                <div class="text-footer">
                    <h3>полезная информация</h3>
                </div>
                <div class="text-footer clearfix">
                    <h3>Оставайтесь на связи</h3>
                    <p>Подписаться на новости и рассылки</p>
                    <form>
                        <input type="email" name="email" placeholder="ваш email">
                        <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                    </form>
                </div>
            </div>
            <p class="small">&copy; GB {% now "Y" %}</p>
            <div class="social">
                <a href="#" class="social1"></a>
                <a href="#" class="social2"></a>
                <a href="#" class="social3"></a>
                <a href="#" class="social4"></a>
            </div>
            <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
        </div>
    {% endblock %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load tags %}
{% block menu %}
    <div class="hero">
        <div class="header clearfix">
            <a href="#" class="logo"></a>
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
        <h1>наши контакты</h1>
    </div>
{% endblock %}
{% block content %}
    <div class="location">
        {% for contact in contacts %}
            <div class="location-1">
                <i class="fa fa-map-marker fa-5x"></i>
                <h4>{{ contact.city }}</h4>
                <div class="contacts">
                    <h5>{% field_name contact 'phone' %}</h5>
                    <p>{{ contact.phone  }}</p>
                </div>
                <div class="contacts">
                    <h5>{% field_name contact 'email' %}</h5>
                    <p>{{ contact.email }}</p>
                </div>
                <div class="contacts">
                    <h5>{% field_name contact 'address' %}</h5>
                    <p>{{ contact.address }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block menu %}
    <div class="slider">
        <div class="header clearfix">
            <a href="index.html" class="logo"></a>
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="#" class="button-order">заказать <img src="{% static "/img/arrow.png" %}" alt=""></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="featured">
        <div class="featured-menu">
                <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img src="{% static "/img/arrow.png" %}" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            {% for product in products %}
                <div class="block">
                    <a href="{% url 'products:product' product.pk%}">
                        <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                        <div class="text">
                            <h3>{{ product.category.name }}</h3>
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.description }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
      <div class="details-slider">
        <div class="slider-product">
          <img src="/media/{{ product.image }}" 
               alt="{{ product.short_desc }}">
        </div>
        <div class="slider-control">
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 1">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 2">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 3">
            </a>
          </div>
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ product.name|title }}</h3>
        <br>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' product.pk %}" class="red-button">
          заказать 
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
            <p>Категория: {{ product.category.name }}</p>
            <p>Описание: {{ product.description }}</p>
            <p>На складе: {{ product.quantity }}</p>
        </div>
      </div>
    </div>

  </div>

  <div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ hot_product.image }}" alt="{{ hot_product.short_desc }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ hot_product.name|title }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ hot_product.price|floatformat:1 }} <span>руб</span></p>
                <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ hot_product.description }}
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="{% static "/img/arrow.png" %}" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for product in same_products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.pk %}"><img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                            <div class="text">
                                <img src="{% static "/img/icon-hover.png" %}" alt="img">
                                <h3>Категория: {{ product.category.name }}</h3>
                                <h4>Название: {{ product.name|title }}</h4>
                                <p>Описание: {{ product.description }}</p>
                                <p>Цена: {{ product.price }}</p>
                                <p>На складе: {{ product.quantity }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="products_list">
            <div class="title clearfix">
                <h2>Категория: "{{ category.name|title }}"</h2>
                <div class="paginator">
                    {% with ''|center:products.paginator.num_pages as range %}
                        {% for _ in range %}
                            {% if forloop.counter == products.number %}
                                <span>{{ forloop.counter }}</span>
                            {% else %}
                                <a style="text-decoration: underline" href="{% url 'products:page' category.pk forloop.counter %}">{{ forloop.counter }}</a>
                            {% endif %}
                        {% endfor %}
                    {% endwith %}
                    {% if products.has_previous %}
                        <a href="{% url 'products:page' category.pk products.previous_page_number %}"><</a>
                    {% endif %}
                    <span class="current">
                        страница {{ products.number }} из
                        {{ products.paginator.num_pages }}
                    </span>
                    {% if products.has_next %}
                        <a href="{% url 'products:page' category.pk products.next_page_number %}">></a>
                    {% endif %}
                </div>
            </div>
            <div class="category-products clearfix">
                {% for product in products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.pk %}">
                            <img src="/media/{{ product.image }}" alt="product">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.description }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}